version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projetos-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=projetos
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - OPENWEATHERMAP_API_KEY=your_api_key_here
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: projetos
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/app
    working_dir: /app
    command: composer install

volumes:
  db_data: